name: Exemplo Artifacts
run-name:  Exemplo de workflow para artifacts, executado por ${{ github.actor }}
on: 
    workflow_dispatch: # Possibilita disparar o workflow manualmente, como nao temos um evento de push ou pull_request, usamos esse evento  
env:
    NOME_ARTEFATO: teste-artefatos 
jobs:
    upload-artifact:
        runs-on: ubuntu-latest
        steps:
            - name: Listagem de arquivos
              run: ls 
            - name: Gerar arquivos arquivos
              run: |
                mkdir arquivos
                echo "Gerando arquivo 1" > ./arquivos/arquivo1.txt
                echo "Gerando arquivo 2" > ./arquivos/arquivo2.txt

            - name: Upload de arquivos
              uses: actions/upload-artifact@v4
              id: upload-artifact # id para referenciar o output
              with:
                name: ${{ env.NOME_ARTEFATO }}
                path: ./arquivos

            - name: Listar arquivos
              run: ls ./arquivos

            - name: URL para obter  os artefatos
              run: |
                echo "URL para obter os artefatos: ${{ steps.upload-artifact.outputs.artifact_url }}"

    download-artifact:
        runs-on: ubuntu-latest
        needs: [upload-artifact]
        steps:
            - name: Listagem de arquivos
              run: ls

            - name: Download de arquivos
              uses: actions/download-artifact@v4
              with:
                name: ${{ env.NOME_ARTEFATO }}

            - name: Listar arquivos
              run: ls   
                
            