name: Exemplo Controle de Fluxo
run-name:  Exemplo de workflow controle de fluxo executado por ${{ github.actor }}
on: 
  push:
jobs: 
  apenas-main:
    if: ${{ github.ref == 'refs/heads/main'}} 
    # Pode usar o containstambem
    name: esse Job Só executa na branch main
    runs-on: ubuntu-latest
    steps: 
      - name: Executando na main
        run: echo "Executando comando na main"
  
  
  
  todas-as-branchs:
    runs-on: ubuntu-latest
    steps:
      - name: Execução em Feature
        if: ${{ contains(github.ref, 'refs/heads/feature') }}
        run: echo "Execução em Feature"

      - name: Execução em HotFix
        if: ${{ contains(github.ref, 'refs/heads/hotfix') }}
        run: echo "Execução em hotfix"

      - name: Execução em Main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "Execução em main"

      - name: Execução em Todos
        run: echo "Execução em todos"
