name: Exemplo de output
run-name:  Exemplo de workflow para output, executado por ${{ github.actor }}
on: 
    workflow_dispatch: # Possibilita disparar o workflow manualmente, como nao temos um evento de push ou pull_request, usamos esse evento
jobs:
    gerando_output:
        runs-on: ubuntu-latest
        outputs:
            output-shell: ${{ steps.exemplo-output.outputs.action_random }}
        steps:
            - name: Gerando os outputs com shell
              id: exemplo-output
              # ">>" inclui e ">" sobreescreve
              run: |
                ACTION_RANDOM=$(( $RANDOM ))
                echo "action_random=$ACTION_RANDOM" >> $GITHUB_OUTPUT 
            - name: Exibindo output da action
              run: echo "${{ steps.exemplo-output.outputs.action_random}}"
    
    
    exibindo_output:
        needs: [gerando_output] # para puxar os outros output  para esse job
        runs-on: ubuntu-latest
        steps:
            - name: Exibindo output do JOB
              run: echo "Output  shell do job:${{ needs.gerando_output.outputs.output-shell }}"