name: Exemplo de output
run-name:  Exemplo de workflow para output, executado por ${{ github.actor }}
on: 
    workflow_dispatch: # Possibilita disparar o workflow manualmente, como nao temos um evento de push ou pull_request, usamos esse evento
jobs:
    gerando_output:
        runs-on: ubuntu-latest
        outputs:
            versao:
            #     description: "Versao da nova release"
            # numero_card:
            #     description: "Numero do card da tarefa desse commit"
            # fazer_deploy:
            #     description: "Se deve ou nao fazer deploy"
            # ambiente:
            #     description: "Ambiente de deploy"
        steps:
            - name: Gerando os outputs com shell
              id: exemplo-output
              # ">>" inclui e ">" sobreescreve
              run: |
                ACTION_RANDOM=$(( $RANDOM ))
                echo "action_random=$ACTION_RANDOM" >> $GITHUB_OUTPUT 
            - name: Exibindo output da action
              run: echo "${{ steps.exemplo-output.outputs.action_random}}"